baseURL = 'https://example.org/'
languageCode = 'pl'
title = 'Żurfiks'

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  mainSections = ["posts"]
  [params.Author]
    name = "Redakcja Żurfiks"
    avatar = "images/logo.png"
    bio = "Kolektyw artystyczny Żurfiks. Piękno, sztuka i odrobina dekadencji."
